### PR TITLE
Optimus MIME

### PR DESCRIPTION
**Pull request by rgbkrk**
transformime_logo

Now we have a logo.

### CODE REVIEW

**Comment by willwhitney** [comment]
This is so great.

**Comment by rgbkrk** [comment]
Just realized this should be white "face paint". Another go, in case anyone likes this better:

transformime_white

annnnnnddd I need a black border around that. Enough image tomfoolery from me. Perhaps @cameronoelsen would want to rev on this? :wink: 

> This is so great.

:smile:

**Comment by cameronoelsen** [comment]
Here is the PNG version of the logo requested by @rgbkrk 

transformimepng

**Comment by cameronoelsen** [comment]
Here is the non jagged version
transformimepng

**Comment by rgbkrk** [comment]
Legit.

**Pull request merged**
