### PR TITLE
Try out JS Standard Style

### PR DESCRIPTION
**Pull request by rgbkrk**
I have been gently nudged into trying out JS Standard Style. Here's transformime adapted to [Standard](https://github.com/feross/standard).

/cc @karissa

### CODE REVIEW

**Comment by rgbkrk** [comment]
If anything, I'm bringing this PR up as a discussion point so we can have somewhat consistent style. I'm also a fan of adding rules to the `.jshintrc` or a `.eslintrc`.

**Comment by karissa** [comment]
Woot! Looks great. FWIW, you can also use `standard-format` to automatically format your

**Comment by karissa** [comment]
@rgbkrk can we merge this?

**Comment by rgbkrk** [comment]
Sure, why not. Let's do this.

**Pull request merged**
