### PR TITLE
Add script to generate api docs

### PR DESCRIPTION
**Pull request by lgeiger**
This PR is based on #59.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Cool cool. Pinging @jdetle and @captainsafia for integration work. We can host this via the GitHub pages certainly, on the `nteract.github.io/transformime` endpoint.

**Comment by jdetle** [comment]
@lgeiger, you fixed a typo of mine, HTMLElement to HTML Element in all of the .js files, but the Documentation page currently still has no spaces for HTMLElement. Is this intentional or a typo to be fixed?

**Comment by lgeiger** [comment]
@jdetle Yes this is intentional. `jsdoc` fails when using "HTML Element".

**Comment by lgeiger** [comment]
I noticed there are some errors in the generated markdown. I'll close this for now

**Pull request closed without merging**
