### PR TITLE
[WIP] Updated transform docs

### PR DESCRIPTION
**Pull request by jdetle**
Addresses #58 

Not sure about some things. I assumed that all data and values are represented as strings? This might be dead wrong but I'm not entirely sure.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Yeah they're all `string`s, they come from the mimetype conventions in [the messaging protocol](http://jupyter-client.readthedocs.io/en/latest/messaging.html) and [the notebook format](http://nbformat.readthedocs.io/en/latest/format_description.html#display-data). This is looking good.

/cc @lgeiger

**Comment by jdetle** [comment]
Thanks, I'm working through the REPL tutorial as we speak to try to understand everything better. It's very well put together!

**Comment by rgbkrk** [comment]
Awesome! I hope there aren't too many cob webs in the REPL tutorial!

**Comment by lgeiger** [comment]
Awesome! Thanks for the docs 👍

**Comment by jdetle** [comment]
Thanks for the functions! I'm learning a lot of new things doing this sort of work :+1:

**Comment by lgeiger** [comment]
@jdetle Is this PR still WIP?

**Comment by jdetle** [comment]
I wrote docs for all the functions, if there is other work left to do
please let me know!
On Wed, Jul 13, 2016 at 9:47 AM Lukas Geiger <notifications@github.com>
wrote:

> @jdetle <https://github.com/jdetle> Is this PR still WIP?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/nteract/transformime/pull/59#issuecomment-232378440>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKcARrvL-jzBOrX2QUzOvQSyx7xcpBxMks5qVPpWgaJpZM4I30WL>
> .
>
-- 
Have a wonderful day,
John J. Detlefs

**Comment by lgeiger** [comment]
I just ask because of the PR title: "[WIP] Updated transform docs".

I think we can merge this. Thanks a lot for taking the time to write the docs 👍 .

**Comment by jdetle** [comment]
Thanks for merging! I thought I changed the title! I hope to contribute
more in the future!
On Wed, Jul 13, 2016 at 9:51 AM Lukas Geiger <notifications@github.com>
wrote:

> I just ask because of the PR title: "[WIP] Updated transform docs".
>
> I think we can merge this. Thanks a lot for taking the time to write the
> docs 👍 .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nteract/transformime/pull/59#issuecomment-232380088>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKcARthcv0V0--4Bh2Ow-cEY1hPam0xGks5qVPuHgaJpZM4I30WL>
> .
>
-- 
Have a wonderful day,
John J. Detlefs

**Comment by rgbkrk** [comment]
Great! I was hoping this would be merged too, I was waiting on the `[WIP]` tag too. Thanks for pinging and merging @lgeiger

**Comment by jdetle** [comment]
Oops! My bad!

On Wed, Jul 13, 2016 at 9:08 AM Kyle Kelley <notifications@github.com>
wrote:

> Great! I was hoping this would be merged too, I was waiting on the [WIP]
> tag too. Thanks for pinging and merging @lgeiger
> <https://github.com/lgeiger>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nteract/transformime/pull/59#issuecomment-232404280>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKcARnFelUH4I29TSf-Q0FcSnMo4v0J9ks5qVQ1jgaJpZM4I30WL>
> .
>
-- 
Have a wonderful day,
John J. Detlefs

**Pull request merged**
