### PR TITLE
Resolve promise promise to @rgbkrk 🍰

### PR DESCRIPTION
**Pull request by jdfreder**
Just "resolving" the "promise" I made on GTalk.

### CODE REVIEW

**Comment by rgbkrk** [comment]
How do we use this with thrown errors?

**Comment by jdfreder** [comment]
I forgot that bit, I'll push another commit.

**Comment by jdfreder** [comment]
@rgbkrk the last commit handles all errors as promise rejections.  Calling one of the transform methods looks something like this:

```js
transformer.transform(args).then((el) => {
    // woot
}).catch((err) => {
    console.error('Error while transforming', err);
});

**Comment by rgbkrk** [comment]
Looks like this will definitely matter for things like PDF rendering via [PDF.js, which relies on Promises heavily](https://mozilla.github.io/pdf.js/examples/).

It seems like it would be the renderers that produce the promises though, not `Transformime`. Would that be fair?

**Comment by jdfreder** [comment]
> It seems like it would be the renderers that produce the promises though, not Transformime. Would that be fair?

Yeah, the current state of the PR allows renderers to return a Promise or a value.  Whatever makes sense for the renderer will work, that's the point of the `Promise.resolve(` sitting in the main transformime class.

**Comment by jdfreder** [comment]
Async horse :horse:

**Comment by rgbkrk** [comment]
Alright, I'll merge this now and just follow on with a testing and doc PR.

**Pull request merged**
